export const types = [
  {
    value: "chandelier",
    label: "Люстры",
    icon: "Lightbulb",
    color: "text-yellow-500",
  },
  {
    value: "ceiling_chandelier",
    label: "Потолочные люстры",
    icon: "Circle",
    color: "text-amber-500",
  },
  {
    value: "pendant_chandelier",
    label: "Подвесные люстры",
    icon: "Droplet",
    color: "text-cyan-500",
  },
  {
    value: "cascade",
    label: "Каскадные",
    icon: "Layers",
    color: "text-indigo-500",
  },
  {
    value: "rod",
    label: "На штанге",
    icon: "Minus",
    color: "text-slate-500",
  },
  {
    value: "large",
    label: "Большие люстры",
    icon: "Maximize2",
    color: "text-rose-500",
  },
  {
    value: "fan_chandelier",
    label: "Люстры-вентиляторы",
    icon: "Fan",
    color: "text-teal-500",
  },
  {
    value: "elite_chandelier",
    label: "Элитные люстры",
    icon: "Crown",
    color: "text-yellow-600",
  },

  {
    value: "light_pendant",
    label: "Подвесные светильники",
    icon: "Droplet",
    color: "text-blue-400",
  },
  {
    value: "light_ceiling",
    label: "Потолочные светильники",
    icon: "Circle",
    color: "text-slate-400",
  },
  {
    value: "light_wall",
    label: "Настенные светильники",
    icon: "Square",
    color: "text-purple-400",
  },
  {
    value: "light_wall_ceiling",
    label: "Настенно-потолочные",
    icon: "LayoutGrid",
    color: "text-indigo-400",
  },
  {
    value: "light_surface",
    label: "Накладные светильники",
    icon: "Box",
    color: "text-emerald-400",
  },
  {
    value: "light_recessed",
    label: "Встраиваемые светильники",
    icon: "CircleDot",
    color: "text-teal-400",
  },
  {
    value: "light_spot",
    label: "Точечные светильники",
    icon: "Dot",
    color: "text-cyan-400",
  },
  {
    value: "light_night",
    label: "Ночники",
    icon: "Moon",
    color: "text-violet-400",
  },
  {
    value: "light_furniture",
    label: "Мебельные",
    icon: "Sofa",
    color: "text-amber-400",
  },
  {
    value: "light_plant",
    label: "Для растений",
    icon: "Leaf",
    color: "text-green-500",
  },
  {
    value: "light_bactericidal",
    label: "Бактерицидные",
    icon: "ShieldPlus",
    color: "text-red-400",
  },
  {
    value: "light_kit",
    label: "Комплекты светильников",
    icon: "Package",
    color: "text-orange-400",
  },
  {
    value: "light_elite",
    label: "Элитные светильники",
    icon: "Crown",
    color: "text-yellow-500",
  },

  {
    value: "lamp_decorative",
    label: "Декоративные лампы",
    icon: "Sparkles",
    color: "text-pink-500",
  },
  {
    value: "lamp_office",
    label: "Офисные лампы",
    icon: "Briefcase",
    color: "text-gray-500",
  },
  {
    value: "lamp_kids",
    label: "Детские лампы",
    icon: "Baby",
    color: "text-pink-400",
  },
  {
    value: "lamp_clip",
    label: "На прищепке",
    icon: "Paperclip",
    color: "text-blue-500",
  },
  {
    value: "lamp_clamp",
    label: "На струбцине",
    icon: "Grip",
    color: "text-slate-500",
  },

  {
    value: "sconce",
    label: "Бра",
    icon: "WallLamp",
    color: "text-purple-500",
  },

  {
    value: "spot_one",
    label: "Спот с 1 плафоном",
    icon: "Circle",
    color: "text-orange-500",
  },
  {
    value: "spot_two",
    label: "Спот с 2 плафонами",
    icon: "CircleDot",
    color: "text-orange-600",
  },
  {
    value: "spot_three_plus",
    label: "Спот с 3+ плафонами",
    icon: "CircleEllipsis",
    color: "text-orange-700",
  },
  {
    value: "spot_recessed",
    label: "Встраиваемые споты",
    icon: "Disc",
    color: "text-amber-600",
  },
  {
    value: "spot_surface",
    label: "Накладные споты",
    icon: "Box",
    color: "text-yellow-600",
  },

  {
    value: "outdoor_street",
    label: "Уличные светильники",
    icon: "Lamp",
    color: "text-slate-600",
  },
  {
    value: "outdoor_landscape",
    label: "Ландшафтные",
    icon: "Trees",
    color: "text-green-600",
  },
  {
    value: "outdoor_architectural",
    label: "Архитектурные",
    icon: "Building",
    color: "text-stone-600",
  },
  {
    value: "outdoor_park",
    label: "Парковые",
    icon: "TreePine",
    color: "text-emerald-600",
  },
  {
    value: "outdoor_wall",
    label: "Уличные настенные",
    icon: "Square",
    color: "text-zinc-600",
  },
  {
    value: "outdoor_console",
    label: "Консольные",
    icon: "Minus",
    color: "text-neutral-600",
  },
  {
    value: "outdoor_ground",
    label: "Грунтовые",
    icon: "Mountain",
    color: "text-brown-600",
  },
  {
    value: "outdoor_underwater",
    label: "Подводные",
    icon: "Waves",
    color: "text-blue-600",
  },
  {
    value: "outdoor_recessed_ground",
    label: "Встраиваемые грунтовые",
    icon: "CircleDot",
    color: "text-teal-600",
  },
  {
    value: "outdoor_ceiling",
    label: "Уличные потолочные",
    icon: "Circle",
    color: "text-gray-600",
  },
  {
    value: "outdoor_bollard",
    label: "Столбики",
    icon: "Cylinder",
    color: "text-stone-500",
  },

  {
    value: "led_strip",
    label: "Светодиодные ленты",
    icon: "Minus",
    color: "text-blue-500",
  },
  {
    value: "led_profile",
    label: "Профили для LED лент",
    icon: "RectangleHorizontal",
    color: "text-slate-500",
  },
  {
    value: "led_neon",
    label: "LED-неон",
    icon: "Zap",
    color: "text-pink-500",
  },

  {
    value: "lamp_table",
    label: "Настольные лампы",
    icon: "Lamp",
    color: "text-orange-500",
  },
  {
    value: "lamp_floor",
    label: "Напольные торшеры",
    icon: "LampFloor",
    color: "text-amber-500",
  },
];

export const categories = [
  {
    value: "chandeliers",
    label: "Люстры",
    icon: "Lightbulb",
    color: "text-yellow-500",
    subcategories: [
      "chandelier",
      "ceiling_chandelier",
      "pendant_chandelier",
      "cascade",
      "rod",
      "large",
      "fan_chandelier",
      "elite_chandelier",
    ],
  },
  {
    value: "lights",
    label: "Светильники",
    icon: "Lamp",
    color: "text-blue-500",
    subcategories: [
      "light_pendant",
      "light_ceiling",
      "light_wall",
      "light_wall_ceiling",
      "light_surface",
      "light_recessed",
      "light_spot",
      "light_night",
      "light_furniture",
      "light_plant",
      "light_bactericidal",
      "light_kit",
      "light_elite",
    ],
  },
  {
    value: "lamps",
    label: "Лампы",
    icon: "LampDesk",
    color: "text-orange-500",
    subcategories: [
      "lamp_table",
      "lamp_floor",
      "lamp_decorative",
      "lamp_office",
      "lamp_kids",
      "lamp_clip",
      "lamp_clamp",
    ],
  },
  {
    value: "sconces",
    label: "Бра",
    icon: "Square",
    color: "text-purple-500",
    subcategories: ["sconce"],
  },
  {
    value: "spots",
    label: "Споты",
    icon: "Circle",
    color: "text-orange-600",
    subcategories: [
      "spot_one",
      "spot_two",
      "spot_three_plus",
      "spot_recessed",
      "spot_surface",
    ],
  },
  {
    value: "outdoor",
    label: "Уличное освещение",
    icon: "Trees",
    color: "text-green-600",
    subcategories: [
      "outdoor_street",
      "outdoor_landscape",
      "outdoor_architectural",
      "outdoor_park",
      "outdoor_wall",
      "outdoor_console",
      "outdoor_ground",
      "outdoor_underwater",
      "outdoor_recessed_ground",
      "outdoor_ceiling",
      "outdoor_bollard",
    ],
  },
  {
    value: "led",
    label: "LED подсветка",
    icon: "Zap",
    color: "text-pink-500",
    subcategories: ["led_strip", "led_profile", "led_neon"],
  },
];
