ALTER TABLE products 
ADD COLUMN IF NOT EXISTS has_remote BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS is_dimmable BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS has_color_change BOOLEAN DEFAULT false;